/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleDEX } from "./SimpleDEX";
export * as factories from "./factories";
export { SimpleDEX__factory } from "./factories/SimpleDEX__factory";
